-- 코드를 작성해주세요
# SELECT FISH_TYPE AS FISH_COUNT, FISH_NAME

# FROM FISH_NAME_INFO
# WHERE (FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE);

SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO F
JOIN FISH_NAME_INFO N
ON F.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY FISH_COUNT DESC;